version: '3'
services:

  mongodb:
    image: mongo:latest
    container_name: dearflow-document-db
    ports:
      - "0.0.0.0:27017:27017"
    network_mode: "bridge"
    volumes:
      - ./api/mongo_data:/data/db
  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:3000:3000"
    network_mode: "bridge"
    volumes:
      - ./app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:4000:4000"
    network_mode: "bridge"
    volumes:
      - ./api:/app
      - /app/node_modules
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    environment:
      - NODE_ENV=development
      - MONGO_DB_CONNECTOR=mongodb://dearflowAdmin:dearflowAdmin123@localhost:27017/dearflow